format_version: 3
pipelines:
  Test1:
    group: TestAGroup
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    materials:
      git:
        git: https://github.com/gkarthikeyangkk/sample-project-maven
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - Stage1:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          Clean:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -c
                - "mvn clean package"
                command: /bin/sh
                run_if: passed
    - Stage2:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          install:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -c
                - "mvn clean package"
                command: /bin/sh
                run_if: passed
